# Generated by Django 4.2.1 on 2023-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
