# Generated by Django 4.2.1 on 2023-07-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
