# Generated by Django 5.0.1 on 2024-02-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_secondary_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="professions",
        ),
        migrations.DeleteModel(
            name="Profession",
        ),
    ]
