# Generated by Django 5.1.1 on 2024-09-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('social', models.CharField(choices=[('github', 'Github'), ('website', 'Website'), ('gitlab', 'GitLab'), ('failed', 'Failed')], default='website', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='registry/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=100)),
                ('socials', models.ManyToManyField(to='packages.packagesocial')),
                ('registry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.registry')),
            ],
        ),
    ]
